spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  #配置注册列表显示名为IP+port
    lease-renewal-interval-in-seconds: 3      # 服务续约间隔时间
    lease-expiration-duration-in-seconds: 7  # 服务续约到期时间
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#  client:
#    service-url:
#      #开发环境
#      defaultZone: http://username:password@ip:8881/eureka/,http://username:password@ip:8882/eureka/
      #测试环境
#      defaultZone: http://username:password@ip:8761/eureka